### ISSUE TITLE
[Mongo] Initial prototype/investigation work

### ISSUE THREAD

**Issue by avanderhoorn** [avanderhoorn/Glimpse.Prototype#108]
Investigate how to tap into the operations being performed (existing logging vs DS, get feedback):
- [ ] Determine what logging is currently in place
  - [ ] Evaluate different ways of being able to get the execution data out 
- [ ] Publish initial messages through message bus _(prototype)_
- [ ] Validate that messages show in the client under the messages tab _(demo)_

**Comment by mike-kaufman** [comment]
Closing this as it no longer reflects known work to be done.
