### ISSUE TITLE
F5 running experience

### ISSUE THREAD

**Issue by nikmd23** [avanderhoorn/Glimpse.Prototype#15]
Once the Glimpse source code has been downloaded, and the `.sln` opened, it should only require users to press `F5` to get the following:
- [x] Glimpse building
- [x] A sample application, most likely [aspnet/musicstore](https://github.com/aspnet/musicstore), popped open in a browser
  - [x] with populated database,
  - [x] Glimpse running in a "single-proc" mode
  - [x] where clicking the "G" will open the full client

Of note, the pieces mentioned in this issue do not need to be fully functioning. For example, the client may be the current "test client".

**Comment by nikmd23** [comment]
While the solution is building, I've not been able to get `Glimpse.AgentServer.AspNet.Sample` to run.

**Comment by avanderhoorn** [comment]
Music store is up and running and in a stable state.
