### ISSUE TITLE
Server Broker extension points?

### ISSUE THREAD

**Issue by avanderhoorn** [avanderhoorn/Glimpse.Prototype#39]
On the Agent Broker we have the ability for authors to be able to tap into the message pipeline on or off the request thread. Do we want the same type of capability with the Server Broker? Here it would be a bit different to the Agent side of things, as the Agent has access to the typed object and the server only has access to an `IMessage`. Is there any benefit of this, do we want to facilitate canceling messages on this side (even though we said we didn't want to in the agent)? 

// @nikmd23

**Comment by nikmd23** [comment]
I could see a few reasons to have this in the future, but I don't think it's necessary now.

**Comment by avanderhoorn** [comment]
Ok, so I'm going to remove the code that I have commented out for the moment.

**Comment by avanderhoorn** [comment]
I ended up putting this in, because the client publisher and store can probably use this hook themselves to this point.
