### ISSUE TITLE
Bug and data structures used by InMemoryStorage

### ISSUE THREAD

**Issue by mike-kaufman** [avanderhoorn/Glimpse.Prototype#55]
One issue with the current implementation of InMemoryStorage class is there's a bug in the logic that removes the "oldest" messages.  Current code is actually removing the most recent message.  You're choosing the message to remove from the tail of the array, but you always append to the list.

One simple solution is continue to use a List, but choose the head of of the array.  RemoveAll from the list is an O(n) operation.  However, this approach would likely result in O(n) shifting.  

Another approach here would be to use a linked list.  Removing/inserting from the LL could be done in O(1) time.  You would still need an O(n) scan of the list to identify nodes to remove, but you could fix this by creating an index structure to look up message nodes by ID.   

E.g., with the following, your clean-up code would become O(logn)

```
LinkedList<Messages> _messages  =...
SortedDictionary<GUID, LinkedListNode<Message>>  _messagesByContextId =  ...
```

and your clean-up code becomes:

```
guid idToRemove = _messages.Last().Context.Id;
foreach (LinkedListNode n in _messagesByContextId.Get(idToRemove)  {
     _messages.Remove(n);
}
_messagesByContextId.Remove(idToRemove);
```

All of the above should be O(log(n)).  You could use a hash table instead of a dictionary and have faster runtime for more memory usage. 

Moreover, you could extend the index structure to support lookups by other values. 

This does have a linear impact on memory overhead. 

Thoughts?   Feedback?

**Comment by nikmd23** [comment]
This issue is being worked on in #62 by @mike-kaufman. I'm closing this issue in favor of that PR.
