### ISSUE TITLE
Setup message resources to work with targeting specific message types

### ISSUE THREAD

**Issue by avanderhoorn** [avanderhoorn/Glimpse.Prototype#56]
Need to setup messages resources so that we can target specific messages types for both stream and history. This might already be done and just needs to be documented/communicated. But this is so that that the client can ask from messages history/stream for specific message types. Currently they will get every message type.

**Comment by nikmd23** [comment]
@avanderhoorn, can you edit the initial comment to provide additional context on this issue? I'm not sure what needs to be done here.

**Comment by avanderhoorn** [comment]
Updated.
