### ISSUE TITLE
Add script to setup dev environment, including automation of dnvm/dnu resets

### ISSUE THREAD

**Issue by mike-kaufman** [avanderhoorn/Glimpse.Prototype#60]

**Comment by mike-kaufman** [comment]
This comes up repeatedly, so I thought it would be useful to automate this as a cmd script.

**Comment by avanderhoorn** [comment]
Looks good. Generally we don't need to create both an issue and a PR if we are intending to create a PR anyway like in this case. Starting with an issue is good if there needs to be discussion before starting.

**Comment by mike-kaufman** [comment]
Cool.   Thanks Anthony.

**Comment by nikmd23** [comment]
Merged PR #61 to fix this issue.
