### ISSUE TITLE
Is this package already pushed to a nuget feed?

### ISSUE THREAD

**Issue by promontis** [avanderhoorn/Glimpse.Prototype#63]
What the titles says :) Would like to use this and wondering whether it is already published

**Comment by avanderhoorn** [comment]
@promontis Thanks for your interest! At the moment there still isn't that much to see. Most of this work represents getting the right hook points in place, making sure our data throughput is good, architecture is right, etc, etc. Work has begun on the UI but the UI is basically just showing raw "messages" there isn't any formatting of the data or anything like that. We are hoping to have a bit more of the UI done by the end of next week. 

If you are interested in seeing things before then or want to get involved early on feedback, etc, the best thing you can do is clone the repo to your local machine somewhere and use `global.json` to point to the `src` folder within the glimpse repo - it might look something like this `[ ..., '../../glimpse.prototype/src' ]`. From there you can add glimpse as an existing project to your solution and add the relevant Glimpse packages to your web project.

I would be keen to know how you get on if you decide to try things out now. So keep us in the loop with how you get on.

**Comment by nikmd23** [comment]
Nothing else to see here. @promontis, please keep an eye on http://blog.getglimpse.com/ for announcements about releases.
