### ISSUE TITLE
Implement HUD

### ISSUE THREAD

**Issue by nikmd23** [avanderhoorn/Glimpse.Prototype#69]
HUD already has a stub implementation at `Glimpse.Server/Internal/Resources/Embeded/Client/hud/hud.js`, but it needs to be fleshed out.

This effort should basically mimic HUD from Glimpse 1.x, without:
- Support for AJAX
- Detailed pop-up's on mouse over

**Comment by avanderhoorn** [comment]
HUD is in and done.
