### ISSUE TITLE
'HttpContext' does not contain a definition for 'ApplicationServices'

### ISSUE THREAD

**Issue by ajtowf** [avanderhoorn/Glimpse.Prototype#85]
Saw Hanselman use glimpse on connect().
Tried following these steps first:
http://blog.getglimpse.com/2015/11/19/installing-glimpse-v2-beta1/
Didn't work out though, the HUD only shows the G, and the client doesn't seem trace db queries.

Checked out this repo, ran: build.cmd 
and got the following error:
C:\dev\Glimpse.Prototype\src\Glimpse.Agent.AspNet\Inspectors\Tab.cs(20,63): DNXCore,Version=v5.0 error CS1061: 'HttpContext' does not contain a definition for 'ApplicationServices' and no extension method 'ApplicationServices' accepting a first argument of type 'HttpContext' could be found (are you missing a using directive or an assembly reference?)

A breaking change in asp.net 5 perhaps? Can't seem to get ApplicationServices from the context.

**Comment by khellang** [comment]
Yes. ApplicationServices was removed. See https://github.com/aspnet/HttpAbstractions/issues/466#issuecomment-158299983. This sounds like #83.

**Comment by nikmd23** [comment]
Sounds like you were building against the dev branch, which is forward looking to the next ASP.NET release. You'll have better luck with the release branch, which is what Hanselman demo'ed.

As far as your original issue (HUD only shows the G), does it look like known issue #83, or something different?

**Comment by ajtowf** [comment]
Right, fixed it though, created a PR, no-brainer.

**Comment by nikmd23** [comment]
You're awesome. Thanks so much Ajden
