### ISSUE TITLE
On Ubuntu 14.04 don`t see panel

### ISSUE THREAD

**Issue by Codenator81** [avanderhoorn/Glimpse.Prototype#89]
When run on Ubuntu Kestrel server got script error:
Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost/glimpse/agent/agent.js?hash=a1dce6fc Failed to load resource: the server responded with a status of 404 (Not Found)

But I serving http://codenator.org not localhost ))

On localhost works ok http://screencast.com/t/tmZ7IRtAK

You can test it on http://codenator.org

**Comment by Codenator81** [comment]
I think problem where in browser cache/ Can`t reproduce any more

**Comment by avanderhoorn** [comment]
Humm thats still really weird as I got the issue when I went to http://codenator.org. Let me know if it happens again.

**Comment by Codenator81** [comment]
@avanderhoorn Still have same bugs. For example on localhost I can see action controller but with domain name action just undefined
